package db

import (
	"context"
	"database/sql"
	"embed"
	"fmt"
	"log/slog"
	"net/url"
	"strings"
	"time"

	"github.com/golang-migrate/migrate/v4"
	"github.com/golang-migrate/migrate/v4/database/sqlite3"
	"github.com/golang-migrate/migrate/v4/source/iofs"
	"github.com/google/uuid"
	db_gen "github.com/maddsua/flippercardapp/db/generated"
	"github.com/maddsua/flippercardapp/db/model"
	"github.com/maddsua/flippercardapp/db/types"
	"github.com/maddsua/flippercardapp/utils"
	"golang.org/x/crypto/bcrypt"

	_ "github.com/mattn/go-sqlite3"
)

func Open(dburl string) (*sql.DB, error) {

	path, query, _ := strings.Cut(dburl, "?")

	opts, err := url.ParseQuery(query)
	if err != nil {
		return nil, fmt.Errorf("parse database url '%s': %v", dburl, err)
	}

	opts.Set("_fk", "true")
	opts.Set("_journal", "WAL")

	dburl = strings.Join([]string{path, opts.Encode()}, "?")

	db, err := sql.Open("sqlite3", dburl)
	if err != nil {
		return nil, fmt.Errorf("open database at '%s': %v", dburl, err)
	}

	if err := db.Ping(); err != nil {
		return nil, fmt.Errorf("open database at '%s': %v", dburl, err)
	}

	return db, nil
}

//go:embed migrations/*
var migrationFS embed.FS

type MigrationState struct {
	Version uint
	Dirty   bool
	Updated bool
}

func Migrate(db *sql.DB) (*MigrationState, error) {

	source, err := iofs.New(migrationFS, "migrations")
	if err != nil {
		return nil, err
	}

	instance, err := sqlite3.WithInstance(db, &sqlite3.Config{})
	if err != nil {
		return nil, err
	}

	migration, err := migrate.NewWithInstance("iofs", source, "sqlite3", instance)
	if err != nil {
		return nil, err
	}

	var upToDate bool

	if err := migration.Up(); err != nil {
		if err == migrate.ErrNoChange {
			upToDate = true
		} else {
			return nil, err
		}
	}

	version, dirty, err := migration.Version()
	if err != nil {
		return nil, err
	}

	return &MigrationState{
		Version: version,
		Dirty:   dirty,
		Updated: !upToDate,
	}, nil
}

func NewWrapper(db *sql.DB) *Wrapper {
	return &Wrapper{
		Queries: *db_gen.New(db),
		db:      db,
	}
}

type Wrapper struct {
	db_gen.Queries
	db *sql.DB
}

func (db *Wrapper) BeginTx(ctx context.Context) (*TxWrapper, error) {

	tx, err := db.db.BeginTx(ctx, nil)
	if err != nil {
		return nil, err
	}

	return &TxWrapper{
		Queries: *db_gen.New(tx),
		tx:      tx,
	}, nil
}

type TxWrapper struct {
	db_gen.Queries
	tx *sql.Tx
}

func (tx *TxWrapper) Rollback() error {
	return tx.tx.Rollback()
}

func (tx *TxWrapper) Commit() error {
	return tx.tx.Commit()
}

func IsNull(err error) bool {
	return err != nil && err.Error() == "sql: no rows in result set"
}

func IsConflict(err error) bool {
	return err != nil && strings.Contains(strings.ToLower(err.Error()), "unique constraint failed")
}

type StateInitParams struct {
	RootUserName     string
	RootUserPassword string
	RestRootPassword bool
}

// todo: refactor
func InitState(db *sql.DB, params StateInitParams) error {

	tx := NewWrapper(db)

	if initUsername := params.RootUserName; initUsername != "" {

		rootUser, err := tx.GetUserByName(context.Background(), initUsername)
		if err != nil && !IsNull(err) {
			return fmt.Errorf("sqlc.GetUserByName: %v", err)
		} else if err == nil {

			if params.RestRootPassword && params.RootUserPassword != "" {

				slog.Warn("Resetting root user password",
					slog.String("id", rootUser.ID.String()),
					slog.String("username", rootUser.Name))

				pwHash, err := bcrypt.GenerateFromPassword([]byte(params.RootUserPassword), bcrypt.DefaultCost)
				if err != nil {
					return fmt.Errorf("bcrypt.GenerateFromPassword: %v", err)
				}

				if rootUser, err = tx.SetUserPassword(context.Background(), db_gen.SetUserPasswordParams{
					ID:           rootUser.ID,
					PasswordHash: pwHash,
				}); err != nil {
					return fmt.Errorf("sqlc.SetUserPassword: %v", err)
				}
			}

			return nil
		}

		initPassword := params.RootUserPassword
		if initPassword == "" {
			initPassword = utils.NewRandomBcryptPassword(64)
		}

		pwHash, err := bcrypt.GenerateFromPassword([]byte(initPassword), bcrypt.DefaultCost)
		if err != nil {
			return fmt.Errorf("bcrypt.GenerateFromPassword: %v", err)
		}

		user, err := tx.InsertUser(context.Background(), db_gen.InsertUserParams{
			ID:           uuid.New(),
			CreatedAt:    types.NewTime(time.Now()),
			Name:         initUsername,
			PasswordHash: pwHash,
			Permissions: model.NullUserPermissions{
				Permissions: model.UserPermissions{
					Administrative: true,
					ContentEdit:    true,
				},
				Valid: true,
			},
		})

		if err != nil {
			return fmt.Errorf("sqlc.InsertUser: %v", err)
		}

		// mask the pass if not autogenerated
		if params.RootUserPassword != "" {
			initPassword = "***"
		}

		slog.Warn("Add a root user",
			slog.String("id", user.ID.String()),
			slog.String("username", initUsername),
			slog.String("password", initPassword))
	}

	return nil
}
