name: Docker publish

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  actions: read
  contents: write
  packages: write

jobs:
  publish-docker:
    name: Build and publish docker image
    runs-on: ubuntu-latest
    env:
      REGISTRY: ghcr.io
      IMAGE_BASE_TAG: ghcr.io/${{ github.repository }}
      IMAGE_TAG: ${{ github.ref_name }}
    steps:
      - name: git checkout
        uses: actions/checkout@v4
        with:
          lfs: true
      - name: Login to ghcr
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Format build timestamp
        id: date
        run: echo "APP_BUILD_TS=$(date -u +'%Y-%m-%dT%H:%M:%SZ')" >> $GITHUB_OUTPUT
      - name: Build and publish action
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          build-args: |
            APP_VERSION=${{ env.IMAGE_TAG }}
            APP_BUILD_TS=${{ steps.date.outputs.APP_BUILD_TS }}
          tags: ${{ env.IMAGE_BASE_TAG }}:${{ env.IMAGE_TAG }}, ${{ env.IMAGE_BASE_TAG }}:latest
